name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    environment:
      name: Prod

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo 'Deploy'
